### ISSUE TITLE
Preference for showing/hiding the dock icon

### ISSUE THREAD

**Issue by paulyoung** [paulyoung/Statusfy#12]

**Comment by pix-art** [comment]
+1

**Comment by elmertoft** [comment]
+1

**Comment by sidewinder12s** [comment]
+1

**Comment by lbinwork** [comment]
+1

**Comment by jameslk** [comment]
Evidently, this can be accomplished by simply following this guide:
http://www.cnet.com/news/prevent-an-applications-dock-icons-from-showing-in-os-x/

That is, the following needs to be appended to `Statusfy.app/Contents/Info.plist` under the `dict` element:

```
<key>LSUIElement</key>
<true/>
```

**Comment by sidewinder12s** [comment]
@jameslk I also found that but that isnt the recommended way from Apple to do this, also you have to restart the App to make the change.

**Comment by jameslk** [comment]
I believe you on that, but since it doesn't seem like your pull request has been merged yet, it was a nice hack for the time being :)

**Comment by sidewinder12s** [comment]
Haha oh ya it works. Actually what I did before I hacked together that pull request.

**Comment by robinvalk** [comment]
+1

**Comment by jsafoodpanda** [comment]
Would this cover the icon when doing Cmd+Tab?

**Comment by nekuz0r** [comment]
Hi, i did merge the pull request from @sidewinder12s and refactor it a bit after in my fork.
https://github.com/nekuz0r/Statusfy

**Comment by Naoto-Ida** [comment]
I've developed a similar app, but don't have the icon in the dock.
Is the decision to have the icon in the dock intentional?
If not, I'd love to send a pull request.

**Comment by jakubzitny** [comment]
+1

**Comment by paulyoung** [comment]
For those wondering, this was this original issue that prompted the return of the dock icon: https://github.com/paulyoung/Statusfy/issues/11

I had hoped to do some refactoring before looking into #15 but clearly that was a long time ago and demand has increased, so I'll take another look soon.
