### ISSUE TITLE
Statusfy not working with latest version of Spotify

### ISSUE THREAD

**Issue by DrZeiss** [paulyoung/Statusfy#14]
This app didn't work when I updated my Spotify app this morning.

**Comment by paulyoung** [comment]
I can confirm that I also see this after updating to version 1.0.1.1060.gc75ebdfd.

Thanks for reporting this @DrZeiss!

**Comment by paulyoung** [comment]
Related links:

* [Bring back Applescript support.](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434)
* [Apple scripting broken in 1.0.1.988.g8f17a348](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434)
* [Latest Spotify version for OS X doesn’t support AppleScripting. Will it be included in future versions of?](http://www.reddit.com/r/spotify/comments/2tpsd3/latest_spotify_version_for_os_x_doesnt_support/)

**Comment by paulyoung** [comment]
As mentioned in [this post](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/m-p/1029434#M109427), AppleScript support appears to have accidentally been broken in the latest version of Spotify.

A workaround for the problem is to open `Spotify.app/Contents/Info.plist` and change:
```plist
<string>Spotify.sdef</string>
```
to:
```plist
<string>applescript/Spotify.sdef</string>
```

**Comment by paulyoung** [comment]
Even though this isn't a bug with Statusfy, I'm going to leave this issue open as long as there's a problem since it'll be more visible that way.

**Comment by radj** [comment]
Can confirm workaround. I had to relaunch both Spotify and Statusfy apps for it to work.

**Comment by DrZeiss** [comment]
I'm also confirming the workaround works.
Thanks for the quick turn around time Paul!

**Comment by sidewinder12s** [comment]
Can confirm that Spotify version 1.0.2.6.g9977a14b does not fix the issue, but the workaround still works.

**Comment by jwboardman** [comment]
Looks like with version 1.0.3.101.gbfa97dfe of Spotify the workaround is no longer necessary, and actually the workaround now breaks Statusfy, so if you have added the "applescript/", remove it.

Perfect little app and just what I was looking for. Thanks!

**Comment by paulyoung** [comment]
Thanks @jwboardman!

Unless I'm mistaken, the update will overwrite any changes to the plist anyway.

Glad this got fixed!
