### ISSUE TITLE
Feature request: simple playback control

### ISSUE THREAD

**Issue by diskostu** [paulyoung/Statusfy#18]
Get some simple playback control (play, pause, forward, rewind) in the menu which appears when clicking on the text in the menubar.

**Comment by copycut** [comment]
There is a analogue project name [bytecontroller](https://github.com/skyfex/bytecontroller) doing that.

**Comment by thedanheller** [comment]
+1

**Comment by k00k** [comment]
For anyone else looking, there's another app available called SmashTunes that gives this and track name as well as some other options. http://smashbits.nl

**Comment by paulyoung** [comment]
Thanks for the suggestion. As others have mentioned, there are other apps offering that sort of functionality, and Statusfy is deliberately more simplistic than that.

Personally, I use the dedicated keys on Apple keyboards for this type of thing.
