### ISSUE TITLE
Option to Launch Spotify

### ISSUE THREAD

**Issue by makiftutuncu** [paulyoung/Statusfy#23]
I usually tend to change the song if I don't like it. After checking what is playing with Statusfy, I wanted to skip the song but I had to go ahead and launch Spotify from my dock. I think it would be nice to have an option to launch Spotify easily from Statusfy.

**Comment by paulyoung** [comment]
Thanks for the suggestion, but is beyond the scope of what I intended with Statusfy.

I often do the same thing and use the F9 key to skip directly, or Command + Tab to switch to Spotify.
