### ISSUE TITLE
Mojave update

### ISSUE THREAD

**Issue by penpadstudio** [paulyoung/Statusfy#39]
@paulyoung 
Hi, Just wondering if you plan to update for the new Mojave OS as Statusfy seems to have stoped working. Great app btw! 👍🏻

**Comment by joshspicer** [comment]
@Pro-Paul I tried to fix Statusfy myself but couldn't figure it out. It was easier for me to rewrite it specifically for Mojave. If you're interested you can get it here: https://github.com/joshspicer/SpotStatus

**Comment by penpadstudio** [comment]
> @Pro-Paul I tried to fix Statusfy myself but couldn't figure it out. It was easier for me to rewrite it specifically for Mojave. If you're interested you can get it here: https://github.com/joshspicer/SpotStatus

@joshspicer nice one. Will take a look. I have been using SpotMenu since: 
https://kmikiy.github.io/SpotMenu
