### ISSUE TITLE
Feature request: Change display format

### ISSUE THREAD

**Issue by malikoth** [paulyoung/Statusfy#7]
Fundamentally, I just want to be able to show "track - album" instead of "track - artist".  I think it would be nice to be able to give a format string to Statusfy and have it replace preset tokens with the corresponding data, but that might take a lot of work.  If you can hack something quick and dirty together though as just an alternative display option, that'd be great too.

I'm a recent convert to MacOS, and I don't know anything about XCode yet.  But if you don't feel like putting this in, I'll look into patching it in and submitting a PR myself at some point in the (distant) future.

**Comment by ch1san** [comment]
personally i wouldn't add any more than artist, title and album, it would be nice if these could be re-ordered; for me i prefer artist - title :)

**Comment by paulyoung** [comment]
Since this is a very old issue, and I'm not inclined to change things too much anymore, I'm going to close this. Thanks for the suggestion.
