### ISSUE TITLE
Truncating long text

### ISSUE THREAD

**Issue by kqr** [paulyoung/Statusfy#8]
The OS X status bar isn't the greatest when it comes to having a lot of stuff there. If an element of it is too long to be visible, that and _all_ the subsequent elements will be hidden. Obviously, this isn't the easiest thing in the world to fix, so my suggestion is being able to truncate long text in Statusfy. This would at least limit the impact of the problem if you pretty much always can see at least 40 characters or whatever.

**Comment by paulyoung** [comment]
I think this is a good idea, and think I may have seen apps with scrolling text in the status bat, but not sure how to go about it exactly.

If someone were to create a pull request for that, I'd consider merging it.

**Comment by paulyoung** [comment]
I think this can be tracked by #29 from now on.
