### ISSUE TITLE
Statusfy is bleeding memory on OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by talanko** [paulyoung/Statusfy#9]
Screenshot taken 20 minutes after launching Statusfy on OS X 10.10 Yosemite.
Before updating to 10.10 this was not an issue.

I left my work laptop open, with Spotify not playing and over night Statusfy ate 26 GB of RAM.

![screen shot 2014-11-06 at 17 28 05](https://cloud.githubusercontent.com/assets/7578976/4938203/be0c6600-65c9-11e4-941d-571554d55841.png)

**Comment by paulyoung** [comment]
I just ran into this.

![screen shot 2015-04-22 at 2 42 45 pm](https://cloud.githubusercontent.com/assets/84700/7286069/f7d3e69e-e8fd-11e4-9313-84302f15b547.png)

**Comment by paulyoung** [comment]
I should note that I haven't rebooted in weeks and have been through multiple sleep/wake cycles.

**Comment by paulyoung** [comment]
This is easily reproducible now. Not sure what changed between Mavericks and Yosemite.

**Comment by paulyoung** [comment]
I haven't been able to reproduce this lately. Anyone else?
